/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LichtLinks_aliases.h"
#include "LichtLinks.h"
#include "MotorLinks_aliases.h"
#include "MotorLinks.h"
#include "VermogenLinks.h"
#include "Klok.h"
#include "MotorRechts_aliases.h"
#include "MotorRechts.h"
#include "VermogenRechts.h"
#include "LichtRechts_aliases.h"
#include "LichtRechts.h"
#include "UART_TRX.h"
#include "GeenIsr0_aliases.h"
#include "GeenIsr0.h"
#include "GeenIsr1_aliases.h"
#include "GeenIsr1.h"
#include "GeenIsr2_aliases.h"
#include "GeenIsr2.h"
#include "RCX_ISR.h"
#include "RTOS_FreeRTOS.h"
#include "RTOS_FreeRTOSConfig.h"
#include "RTOS_READ_ME.h"
#include "setmotoren_Task.h"
#include "UART_RCX.h"
#include "getSensoren_Task.h"
#include "RCX_Task_Task.h"
#include "TRX_Task_Task.h"
#include "UART_TRX_IntClock.h"
#include "UART_RCX_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

